### ISSUE TITLE
just to add that ClamAV has some known CVEs pre-0.98.7 (http://www.cvedetails.com/vulnerability-list/vendor_id-8871/Clamav.html )

### ISSUE THREAD

**Issue by PurpleBooth** [UKHomeOffice/docker-clamav#2]
just to add that ClamAV has some known CVEs pre-0.98.7 (http://www.cvedetails.com/vulnerability-list/vendor_id-8871/Clamav.html )

**Comment by lewismarshall** [comment]
Not sure why the assumption it's running the wrong version? The container does indeed have the latest version:

```
$ docker run -d --name test clamav && docker exec -it test clamd --version
fd50863c7218cf49c111ec884765852ba8170ff716f999e4061259442486de14
ClamAV 0.98.7/20957/Thu Oct  8 23:14:13 2015
```

:-1:
