### ISSUE TITLE
Add a clamd.timeout to handle large files (>10MB)

### ISSUE THREAD

**Issue by digitalronin** [UKHomeOffice/docker-clamav#22]
Files larger than around 10MB will usually cause an error from clamav-rest, unless the bootstrap.sh script is modified to include a clamd.timeout in milliseconds.

Please see this commit for details; https://github.com/ministryofjustice/moj-clamav-rest/commit/c9670b62551e6d12953c879ecbdbadd085b514a7

**Comment by jaykeshur** [comment]
Done by #30
