### ISSUE TITLE
Overwrite configuration

### ISSUE THREAD

**Issue by misgina** [UKHomeOffice/docker-clamav#25]
Our app supports uploading of up to 50M file size, but since in the configuration file the variable StreamMaxLength is set to 25MB we are getting error _INSTREAM size limit exceeded_. Is there a way to change this value.
I have try to add an environment variable (CLAMD_SETTINGS_CSV="StreamMaxLength 50M") as the documentation suggested, but still is not working.

Any clue?

**Comment by irab** [comment]
Maybe try setting 'MaxFileSize 50M'? 

From the doco:

**MaxFileSize SIZE**
    Files larger than this limit won't be scanned. Affects the input file itself as well as files contained inside it (when the input file is an archive, a document or some other kind of container). Warning: disabling this limit or setting it too high may result in severe damage to the system.
    Default: 25M

**Comment by GJKrupa** [comment]
That configuration option is documented but not actually implemented.

**Comment by jaykeshur** [comment]
This is now implemented via #28
