### ISSUE TITLE
Cannot build container

### ISSUE THREAD

**Issue by jeppert** [UKHomeOffice/docker-clamav#45]
running  
> docker build --rm -f Dockerfile" -t docker-clamav:latest

will fail at step 9 
> COPY --chown=clamav:clamav eicar.com /

with the error: 
COPY failed: stat /var/lib/docker/tmp/docker-builder403330422/eicar.com: no such file or directory

I have tried to look inside the image and there is no eicar file anywhere

**Comment by jaykeshur** [comment]
Its because your local virus scanner has quarantined the file, most likely. The eicar.com file is committed to git, so you should be able to confirm this.
